// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7c7CggFuk2K309T3aKsDYuTD-igQlvms',
    appId: '1:584031971776:web:0eb12a5916f7d231dd8025',
    messagingSenderId: '584031971776',
    projectId: 'assignmen-app',
    authDomain: 'assignmen-app.firebaseapp.com',
    storageBucket: 'assignmen-app.appspot.com',
    measurementId: 'G-84EKCCSBQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZWrWBuUPH_NgiHbzlYiqLqH7rYH0daw',
    appId: '1:584031971776:android:32d4d5a87a23d853dd8025',
    messagingSenderId: '584031971776',
    projectId: 'assignmen-app',
    storageBucket: 'assignmen-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGduDuilgr3V5Azsk-Zt4a3tiihxyk700',
    appId: '1:584031971776:ios:8fba9e9c2a83f2b0dd8025',
    messagingSenderId: '584031971776',
    projectId: 'assignmen-app',
    storageBucket: 'assignmen-app.appspot.com',
    iosBundleId: 'com.example.assignmentWebApp',
  );

}